#3028
class Stack:
     def __init__(self):
         self.items = []

     def isEmpty(self):
         return self.items == []

     def push(self, item):
         self.items.append(item)

     def pop(self):
         return self.items.pop()
        
     def size(self):
         return len(self.items)
        
s=Stack()
print(s.isEmpty())
s.push(4)
s.push(8)
s.push(10)
s.push('hey')
s.push('hola')
print(s.size())
print(s.isEmpty())
s.push(8.4)
print(s.pop())
print(s.pop())
print(s.size())